### ISSUE TITLE
Image view redesign

### ISSUE THREAD

**Issue by jakecarlson1** [ImageStyle/ImStyle#14]
Ian and I were talking about redesigning the image view to make the image take up the whole screen. The image will show video from the camera and allow the user to take a picture. That picture would then become the displayed frame.

This would allow the app to connect to the camera earlier which could be used to reduce the load time of the video feed view. This may void the need for a tool tip telling the user to select/take a picture.

We may want to merge this with the video feed view, adding a button to run SF on the video feed. We would then separate out the functionality allowing a user to choose a picture (or a video) from their photo library.

This is a large redesign that will likely involve dropping the tab bar in favor of a multi-windowed view.

**Comment by ianstenbit** [comment]
Closed in PR #16
