### ISSUE TITLE
Style picker image preview

### ISSUE THREAD

**Issue by jakecarlson1** [ImageStyle/ImStyle#18]
They style picker should show a preview of the source style image next to the name of the style.

**Comment by jakecarlson1** [comment]
Also the color of the picker view should extend to include the safe area above it.

**Comment by ianstenbit** [comment]
This is changed by #31. I think what we should do is the following:
Whenever we switch styles by swiping, the new style's base image should briefly fade in and out somewhere on the screen to show what is being used as the base style.
