### ISSUE TITLE
Load image scaling

### ISSUE THREAD

**Issue by jakecarlson1** [ImageStyle/ImStyle#37]
It looks like images loaded from the photo library are being stretched vertically. It's great looking skinnier, but I think we should try to display the images as close as possible to the original image.

**Comment by jakecarlson1** [comment]
This should include scaling images appropriately when displaying the transferred image and saving to camera roll. Currently, grey borders are displayed on each side of the stylized image when displayed.

**Comment by jakecarlson1** [comment]
Now that PR #66 has added video support, this should be expanded to include video scaling. One hold back on this is that the current models only support 720x720 images. However, scaling the image to square and then applying aspect fill still produces an image that looks close to natural. We should start by saving close to this aspect ratio.

**Comment by ianstenbit** [comment]
Your video input implementation already performs the scaling. I've added it for video input in PR #73
