### ISSUE TITLE
Cancel video transfer

### ISSUE THREAD

**Issue by ianstenbit** [ImageStyle/ImStyle#41]
There should be a way to cancel a video transfer while it's happening.

**Comment by jakecarlson1** [comment]
Swiping back to no style should cancel this as well.

**Comment by ianstenbit** [comment]
This is a bit of a design question, because as I mentioned in #44 I would like to disable swipe gestures during transfer. Thoughts?

**Comment by jakecarlson1** [comment]
Just saw that. From a usability standpoint I think swiping should cancel the current video transfer and start the next style. When we have more than two styles, user may want to swipe through a few to get to the one they want. They shouldn't have to wait at each style.
