### ISSUE TITLE
Load video

### ISSUE THREAD

**Issue by jakecarlson1** [ImageStyle/ImStyle#53]
Users should be able to load videos from their camera roll. Based on this post, to allow videos to be selected from the ImagePickerController, we just need to specify allowed media types in our openPhotoLibrary function:
https://stackoverflow.com/questions/30715212/select-video-from-photolibrary-in-ios-using-swift

After that it is just a matter of recognizing if a video or image has been selected and running the corresponding transfer.

We may want to limit the max video length until we have faster style networks?

**Comment by ianstenbit** [comment]
This will be a bit complex because we need to re-format the video as an array of UIImages.
