### ISSUE TITLE
Stylize image with all styles in background when a photo is captured.

### ISSUE THREAD

**Issue by ianstenbit** [ImageStyle/ImStyle#55]
This way, there won't be latency switching over to the stylized image.

**Comment by ianstenbit** [comment]
This is part of an over-arching goal to avoid the whole 'prevImage' object as it's a bit of a hack and that should be improved.

**Comment by jakecarlson1** [comment]
I agree saving an array of stylized images would be better. Making this a parallel array to the style names would mean we can use the currentStyle variable to quickly load an image. However, as the number of styles increases running them all in background would start to cause a bit of a performance issue don’t you think? In the future it might make sense to preload the 3-5 most frequent styles the user uses and load the others on demand.

**Comment by ianstenbit** [comment]
Could be. This will depend on how much we scale this. Realistically, it's reasonably cheap to save a dozen or so UIImages that are 720x720
