### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by jakecarlson1** [ImageStyle/ImStyle#63]
Need to check that the images we used for the app icon background are not copyrighted before releasing. Should change the text on the icon as well.

**Comment by ianstenbit** [comment]
This should be accompanied by a new loading screen.

**Comment by jakecarlson1** [comment]
It looks like the triangles image is from a tumblr post and does not have an author attributed (or they deleted their tumblr page, idk how tumblr works) 
http://aplaceforart.tumblr.com/post/22187675202/jessicastock-painting-a-day-watercolor-11
